# docker-compose up
# docker run -p 5432:5432 -d -e POSTGRES_PASSWORD=password -e POSTGRES_USER=postgres -e POSTGRES_DB=postgresdb postgres
# docker run -p 6379:6379 -d redis
version: "3.9"

services:
  postgresdb:
    image: postgres
    container_name: postgrescontainer
    ports:
      - 5432:5432
    environment:
        POSTGRES_PASSWORD: "password"
        POSTGRES_USER: "postgres"
        POSTGRES_DB: "postgresdb"
  redisdb:
    image: redis
    container_name: rediscontainer
    ports:
      - 6379:6379
  account:
    image: account
    container_name: accountcontainer
    ports:
      - 5000:80
    volumes:
      - .%USERPROFILE%\.aspnet\https:/https/
  trademarket:
    image: trademarket
    container_name: trademarketcontainer
    ports:
      - 5005:80
    volumes:
      - .%USERPROFILE%\.aspnet\https:/https/
    environment:
      ACCOUNT_CONNECTION_STRING: "http://host.docker.internal:5000"
      ASPNETCORE_ENVIRONMENT: "Development"
      REDIS_CONNECTION_STRING: "host.docker.internal:6379"
  facade:
    image: facade
    container_name: facadecontainer
    ports:
      - 5002:80
    volumes:
      - .%USERPROFILE%\.aspnet\https:/https/
    environment:
      ACCOUNT_CONNECTION_STRING: "http://host.docker.internal:5000"
      RELAY_CONNECTION_STRING: "http://host.docker.internal:5004"
      ASPNETCORE_ENVIRONMENT: "Development"
      HISTORY_CONNECTION_STRING: "http://host.docker.internal:5007"
      TRADEMARKET_CONNECTION_STRING: "http://host.docker.internal:5005"

  relay:
    image: relay
    container_name: relaycontainer
    ports:
      - 5004:80
    volumes:
      - .%USERPROFILE%\.aspnet\https:/https/
    environment:
      ALGORITHM_CONNECTION_STRING: "http://host.docker.internal:5006"
      FORMER_CONNECTION_STRING: "http://host.docker.internal:5003"
      ASPNETCORE_ENVIRONMENT: "Development"
      TRADEMARKET_CONNECTION_STRING: "http://host.docker.internal:5005"
  algorithm:
    image: algorithm
    container_name: algorithmcontainer
    ports:
      - 5006:80
    volumes:
      - .%USERPROFILE%\.aspnet\https:/https/
    environment:
      FORMER_CONNECTION_STRING: "http://host.docker.internal:5003"
      ASPNETCORE_ENVIRONMENT: "Development"
  history:
    image: history
    container_name: historycontainer
    ports:
      - 5007:80
    volumes:
      - .%USERPROFILE%\.aspnet\https:/https/
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      POSTGRES_CONNECTION_STRING: "Host=host.docker.internal;Port=5432;Database=historydb;Username=postgres;Password=password"
  former:
    image: former
    container_name: formercontainer
    ports:
      - 5003:80
    volumes:
      - .%USERPROFILE%\.aspnet\https:/https/
    environment:
      HISTORY_CONNECTION_STRING: "http://host.docker.internal:5007"
      TRADEMARKET_CONNECTION_STRING: "http://host.docker.internal:5005"
      RETRY_DELAY: "10000"
    