# docker-compose up 
version: "3.9"

services:
  facade:
    image: facade
    container_name: facadecontainer
    ports:
      - 5002:80
    volumes:
      - .%USERPROFILE%\.aspnet\https:/https/
    environment:
      ACCOUNT_CONNECTION_STRING: "http://localhost:5000"
      RELAY_CONNECTION_STRING: "http://localhost:5004"
      ASPNETCORE_ENVIRONMENT: "Development"
      HISTORY_CONNECTION_STRING: "http://localhost:5007"
      TRADEMARKET_CONNECTION_STRING: "http://localhost:5005"
  relay:
    image: relay
    container_name: relaycontainer
    ports:
      - 5004:80
    volumes:
      - .%USERPROFILE%\.aspnet\https:/https/
    environment:
      ALGORITHM_CONNECTION_STRING": "http://localhost:5006"
      FORMER_CONNECTION_STRING: "http://localhost:5003"
      ASPNETCORE_ENVIRONMENT: "Development"
      TRADEMARKET_CONNECTION_STRING: "http://localhost:5005"
  algorithm:
    image: algorithm
    container_name: algorithmcontainer
    ports:
      - 5006:80
    volumes:
      - .%USERPROFILE%\.aspnet\https:/https/
    environment:
      FORMER_CONNECTION_STRING: "http://localhost:5003"
      ASPNETCORE_ENVIRONMENT: "Development"
  history:
    image: history
    container_name: historycontainer
    ports:
      - 5007:80
    volumes:
      - .%USERPROFILE%\.aspnet\https:/https/
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
  former:
    image: former
    container_name: formercontainer
    ports:
      - 5003:80
    volumes:
      - .%USERPROFILE%\.aspnet\https:/https/
    environment:
      HISTORY_CONNECTION_STRING: "http://host.docker.internal:5007"
      TRADEMARKET_CONNECTION_STRING: "http://host.docker.internal:5005"
      RETRY_DELAY: "10000"
    