# docker-compose up
# docker run -p 5432:5432 -d -e POSTGRES_PASSWORD=password -e POSTGRES_USER=postgres -e POSTGRES_DB=postgresdb postgres
# docker run --rm -it -p 5000:80 -e ASPNETCORE_URLS="http://+;" -e POSTGRES_CONNECTION_STRING=Host=host.docker.internal;Port=5432;Database=account;Username=postgres;Password=password account
# docker run -p 6379:6379 -d redis
# docker run --name seq -d -e ACCEPT_EULA=Y -p 5341:80 datalust/seq:latest
version: "3.9"

services:
  postgresdb:
    image: postgres
    container_name: postgrescontainer
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgresdb"
  redisdb:
    image: redis
    container_name: rediscontainer
    ports:
      - 6379:6379
  seq:
    image: seq
    container_name: seqcontainer
    ports:
     - 5341:80
    environment:
      ACCEPT_EULA: "Y"
  account:
    image: account
    container_name: accountcontainer
    build:      
      context: .
      dockerfile: ./Account/Dockerfile
    ports:
      - 5000:80
    volumes:
      - .%USERPROFILE%\.aspnet\https:/https/
    environment:
      POSTGRES_CONNECTION_STRING: "Host=host.docker.internal;Port=5432;Database=accountdb;Username=postgres;Password=password"
  trademarket:
    image: trademarket
    container_name: trademarketcontainer
    build:      
      context: .
      dockerfile: ./TradeMarket/Dockerfile
    ports:
      - 5005:80
    volumes:
      - .%USERPROFILE%\.aspnet\https:/https/
    environment:
      ACCOUNT_CONNECTION_STRING: "http://host.docker.internal:5000"
      ASPNETCORE_ENVIRONMENT: "Development"
      REDIS_CONNECTION_STRING: "host.docker.internal:6379"
      SEQ_CONNTECTION_STRING: "http://host.docker.internal:5341"
  facade:
    image: facade
    container_name: facadecontainer
    build:      
      context: .
      dockerfile: ./Facade/Dockerfile
    ports:
      - 5002:80
    volumes:
      - .%USERPROFILE%\.aspnet\https:/https/
    environment:
      ACCOUNT_CONNECTION_STRING: "http://host.docker.internal:5000"
      RELAY_CONNECTION_STRING: "http://host.docker.internal:5004"
      ASPNETCORE_ENVIRONMENT: "Development"
      HISTORY_CONNECTION_STRING: "http://host.docker.internal:5007"
      SEQ_CONNECTION_STRING: "http://host.docker.internal:5341"
      TRADEMARKET_CONNECTION_STRING: "http://host.docker.internal:5005"
  relay:
    image: relay
    container_name: relaycontainer
    build:      
      context: .
      dockerfile: ./Relay/Dockerfile
    ports:
      - 5004:80
    volumes:
      - .%USERPROFILE%\.aspnet\https:/https/
    environment:
      ALGORITHM_CONNECTION_STRING: "http://host.docker.internal:5006"
      FORMER_CONNECTION_STRING: "http://host.docker.internal:5003"
      ASPNETCORE_ENVIRONMENT: "Development"
      SEQ_CONNECTION_STRING: "http://host.docker.internal:5341"
      TRADEMARKET_CONNECTION_STRING: "http://host.docker.internal:5005"
  algorithm:
    image: algorithm
    container_name: algorithmcontainer
    build:      
      context: .
      dockerfile: ./Algorithm/Dockerfile
    ports:
      - 5006:80
    volumes:
      - .%USERPROFILE%\.aspnet\https:/https/
    environment:
      SEQ_CONNECTION_STRING: "http://host.docker.internal:5341"
      FORMER_CONNECTION_STRING: "http://host.docker.internal:5003"
      ASPNETCORE_ENVIRONMENT: "Development"
  history:
    image: history
    container_name: historycontainer
    build:      
      context: .
      dockerfile: ./History/Dockerfile
    ports:
      - 5007:80
    volumes:
      - .%USERPROFILE%\.aspnet\https:/https/
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      POSTGRES_CONNECTION_STRING: "Host=host.docker.internal;Port=5432;Database=historydb;Username=postgres;Password=password"
  former:
    image: former
    container_name: formercontainer
    build:      
      context: .
      dockerfile: ./Former/Dockerfile
    ports:
      - 5003:80
    volumes:
      - .%USERPROFILE%\.aspnet\https:/https/
    environment:
      HISTORY_CONNECTION_STRING: "http://host.docker.internal:5007"
      TRADEMARKET_CONNECTION_STRING: "http://host.docker.internal:5005"
      SEQ_CONNECTION_STRING: "http://host.docker.internal:5341"
      RETRY_DELAY: "10000"
    